### ISSUE TITLE
Simple Sample is not working

### ISSUE THREAD

**Issue by Pro100rus32** [Andrey1994/screen_recorder_sdk#12]
win10 x64
monitor: 1366x768

```
Traceback (most recent call last):
  File "E:\ChatBotAI\AiCharli.py", line 28, in <module>
    main ()
  File "E:\ChatBotAI\AiCharli.py", line 10, in main
    pid = int (sys.argv[1]) # pid == 0 means capture full screen
IndexError: list index out of range

Process returned 1 (0x1)        execution time : 0.299 s
```

**Comment by Andrey1994** [comment]
You run it wrong, this samples expects cmd argument which you didnt provide
