### ISSUE TITLE
Error in System Arguments 

### ISSUE THREAD

**Issue by varchasa** [Andrey1994/screen_recorder_sdk#15]
Traceback (most recent call last):
  File "E:\python prog\screen_recorder.py", line 85, in <module>
    main ()
  File "E:\python prog\screen_recorder.py", line 67, in main
    pid = int (sys.argv[1]) # pid == 0 means capture full screen
IndexError: list index out of range

**Comment by Andrey1994** [comment]
python E:\python_prog\screen_recorder.py 0
